doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                OAuth:
                    is_bundle: false
                    type: yml
                    dir: '%kernel.project_dir%/config/doctrine/metadata/mongodb'
                    prefix: Cerberus\OAuth
                    alias: Cerberus
