sudo: required

language: php

services:
  - docker

before_install:
  - docker-compose build server
  - docker-compose -f docker-compose.test.yml up -d mongo

script:
  - docker run -it --rm cerberus/php:7.2 bin/phpunit --testsuite unit
  - docker run -it --rm cerberus/php:7.2 vendor/bin/phpstan analyze src --level 7
  - docker run -it --rm cerberus/php:7.2 vendor/bin/phpcs src --standard=PSR2
  - docker-compose -f docker-compose.test.yml run functional_test
  - docker-compose -f docker-compose.test.yml run integration_test