version: '3.3'

services:
  server:
    image: cerberus/php:7.2
    ports:
      - 8080:8080
#    networks:
#      - proxy
#      - default
#    labels:
#      - traefik.docker.network=proxy
#      - traefik.enable=true
#      - traefik.port=8080
#      - traefik.backend=auth
#      - traefik.frontend.rule=Host:cerberus.dev
#      - traefik.frontend.entryPoints=http,https

  mongo:
    image: mongo:3
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  proxy:
    external: true
  default:
