version: '3.3'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_ID=${USER_ID}
    environment:
      - APP_ENV=dev
    volumes:
      - .:/var/www/html