version: '3.3'

services:
  functional_test:
    image: cerberus/php:7.2
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=test
    command: ["bin/phpunit", "--testsuite", "functional"]

  integration_test:
    image: cerberus/php:7.2
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=test
    command: ["bin/phpunit", "--testsuite", "integration"]

  mongo:
    image: mongo:3
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-test-data:
    driver: local
