version: '3.3'

services:
  server:
    image: cerberus/php:7.2
    build:
      context: ./docker/php
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/app/public"]

  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    external: true
