version: '3.3'

services:
  server:
    image: cerberus/php:7.2
    ports:
      - 8080:8080

  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
