Cerberus\OAuth\Client:
  fields:
    id:
      id: true
      strategy: none
      type: uuid
    name:
      type: string
    clientSecret:
      type: string
    redirectUris:
      type: collection
    allowedGrantTypes:
      type: collection