Cerberus\OAuth\User:
  fields:
    id:
      id: true
      strategy: none
      type: uuid
    username:
      type: string
      index: true
      unique: true
    password:
      type: string
    scopes:
      type: collection
