access_token_request:
    path: /access-token
    methods: [POST]
    controller: Cerberus\Controller\OAuthController::accessTokenRequest

create_client:
    path: /api/client
    methods: [POST]
    controller: Cerberus\Controller\ClientController::create
