access_token_request:
    path: /access-token
    methods: [POST]
    controller: Cerberus\Controller\OAuthController::accessTokenRequest

client_create:
    path: /api/client
    methods: [POST]
    controller: Cerberus\Controller\ClientController::create

client_find_many:
    path: /api/client
    methods: [GET]
    controller: Cerberus\Controller\ClientController::findPaginated

client_find:
    path: /api/client/{id}
    methods: [GET]
    controller: Cerberus\Controller\ClientController::find

client_update:
    path: /api/client/{id}
    methods: [PUT]
    controller: Cerberus\Controller\ClientController::update

client_delete:
    path: /api/client/{id}
    methods: [DELETE]
    controller: Cerberus\Controller\ClientController::delete

user_create:
    path: /api/user
    methods: [POST]
    controller: Cerberus\Controller\UserController::create

user_find_many:
    path: /api/user
    methods: [GET]
    controller: Cerberus\Controller\UserController::findPaginated
