access_token_request:
    path: /access-token
    methods: [POST]
    controller: Cerberus\Controller\OAuthController::accessTokenRequest

client_create:
    path: /api/client
    methods: [POST]
    controller: Cerberus\Controller\ClientController::create

client_find:
    path: /api/client
    methods: [GET]
    controller: Cerberus\Controller\ClientController::findPaginated
